"""Checkpoint loading helpers.

PyTorch 2.6 changed ``torch.load`` to default to ``weights_only=True``.
Our local experiment checkpoints intentionally store metadata such as args,
metrics, and NumPy scalar values in addition to model weights.  Those files
must be loaded with ``weights_only=False``.
"""
from pathlib import Path
from typing import Union

import torch


def load_checkpoint(path: Union[str, Path], map_location="cpu"):
    """Load a trusted local SA-HMARL checkpoint.

    Use this only for checkpoints generated by this project.  Passing
    ``weights_only=False`` allows PyTorch to unpickle metadata stored alongside
    model weights.
    """
    try:
        return torch.load(str(path), map_location=map_location, weights_only=False)
    except TypeError:
        # Older PyTorch versions do not expose the weights_only argument.
        return torch.load(str(path), map_location=map_location)
